---
title: "Titanic"
author: "Calum You"
date: "24th January, 2018"
output:
  html_notebook:
    highlight: tango
    mathjax: null
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_float: yes
---

# Setup
```{r setup}
library(tidyverse)
library(magrittr)
library(rpart)
library(broom)
library(randomForest)
```

# Input
```{r input}
test <- read_csv(here::here("titanic", "data", "test.csv"))
train <- read_csv(here::here("titanic", "data", "train.csv"))

# Combine data into one frame to guarantee the same tranformations
titanic <- list(train = train, test = test) %>%
  bind_rows(.id = "type") %>%
  set_colnames(str_to_lower(colnames(.))) %>%
  mutate_at(vars(age, fare), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)) %>%
  mutate_at(vars(type, sex, pclass, embarked), fac)
```
# Everyone Dies
```{r alldead}
alldead <- titanic %>%
  filter(type == "test") %>%
  mutate(survived = 0) %>%
  select(passengerid, survived)
write_csv(alldead, here::here("titanic", "submissions", "1_alldead.csv"))
```

# Women Live
```{r womenlive}
womenlive <- titanic %>%
  filter(type == "test") %>%
  mutate(survived = ifelse(sex == "female", 1, 0)) %>%
  select(passengerid, survived)
write_csv(womenlive, here::here("titanic", "submissions", "2_womenlive.csv"))
```

# Logistic Regression
```{r}
logit <- glm(
  formula = survived ~ pclass + sex + age + sibsp + parch + fare + embarked,
  family = binomial(link = "logit"),
  data = titanic %>% filter(type == "train")
  )
logistic <- titanic %>%
  filter(type == "test") %>%
  mutate(survived = ifelse(predict(logit, .) > 0.5, 1, 0))
write_csv(
  logistic ,
  here::here("titanic", "submissions", "3_logit.csv")
  )
```

# Decision Tree
```{r}
dtree <- rpart(
  formula = survived ~ pclass + sex + age + sibsp + parch + fare + embarked,
  method = "class",
  data = titanic %>% filter(type == "train")
)
decision <- titanic %>%
  filter(type == "test") %>%
  mutate(survived = predict(dtree, ., type = "class"))
write_csv(
  decision %>% select(passengerid, survived),
  here::here("titanic", "submissions", "4_dtree.csv")
  )
```

# Feature Engineering
```{r}
titanic <- titanic %>%
  mutate(
    title = str_extract(name, "(?<=, )[A-z ]*(?=\\. )"),
    title = fct_collapse(
      .f = factor(title),
      Mrs = c("Mrs", "Mme"),
      Miss = c("Miss", "Mlle"),
      Sir = c("Capt", "Col", "Don", "Major", "Sir"),
      Lady = c("Dona", "Lady", "Jonkheer", "the Countess")
      ),
    surname = str_extract(name, "^.*(?=,)"),
    familysize = sibsp + parch
    )
ftree <- rpart(
  formula = survived ~
    pclass + sex + age + sibsp + parch + fare + embarked + title + familysize,
  method = "class",
  data = titanic %>% filter(type == "train")
)
fdecision <- titanic %>%
  filter(type == "test") %>%
  mutate(survived = predict(ftree, ., type = "class"))
write_csv(
  fdecision %>% select(passengerid, survived),
  here::here("titanic", "submissions", "5_ftree.csv")
  )
```

```{r}
train_t <- titanic %>%
  filter(type == "train") %>%
  mutate_if(is.character, ~ factor(.)) %>%
  na.exclude()
forest <- randomForest(
  formula = as.factor(survived) ~
    pclass + sex + age + sibsp + parch + fare + embarked + title + familysize,
  data = train_t,
  importance = TRUE,
  ntree = 2000
)
varImpPlot(forest)
rforest <- titanic %>%
  filter(type == "test") %>%
  mutate_if(is.character, ~ factor(.)) %>%
  mutate(survived = predict(forest, .))
write_csv(
  rforest %>% select(passengerid, survived),
  here::here("titanic", "submissions", "6_rforest.csv")
  )
```

